export const Symbols = {
    TRANSPORT_FEE_REPOSITORY: Symbol.for('TRANSPORT_FEE_REPOSITORY'),
    USER_REPOSITORY: Symbol.for("USER_REPOSITORY"),
    PRODUCT_REPOSITORY: Symbol.for("PRODUCT_REPOSITORY"),
    IMAGE_REPOSITORY: Symbol.for('IMAGE_REPOSITORY'),
    PRODUCT_CATEGORY_REPOSITORY: Symbol.for('PRODUCT_CATEGORY_REPOSITORY'),
    ORDER_REPOSITORY: Symbol.for('ORDER_REPOSITORY'),
}